import { 
  User, 
  Course, 
  Enrollment, 
  Inquiry, 
  Timetable, 
  Content, 
  ActivityLog,
  DashboardMetrics 
} from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1-234-567-8900',
    role: 'Admin',
    type: 'admin_staff',
    status: 'active',
    createdAt: '2024-01-15T10:00:00Z',
    lastLogin: '2024-12-20T08:30:00Z',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1-234-567-8901',
    role: 'Teacher',
    type: 'teacher',
    status: 'active',
    createdAt: '2024-02-10T10:00:00Z',
    lastLogin: '2024-12-19T14:20:00Z',
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '+1-234-567-8902',
    role: 'Student',
    type: 'student',
    status: 'active',
    createdAt: '2024-03-05T10:00:00Z',
    lastLogin: '2024-12-18T09:15:00Z',
  },
  {
    id: '4',
    name: 'Bob Williams',
    email: 'bob@example.com',
    phone: '+1-234-567-8903',
    role: 'Admin',
    type: 'admin_staff',
    status: 'active',
    createdAt: '2024-04-20T10:00:00Z',
    lastLogin: '2024-12-20T10:45:00Z',
  },
  {
    id: '5',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    phone: '+1-234-567-8904',
    role: 'Teacher',
    type: 'teacher',
    status: 'suspended',
    createdAt: '2024-05-12T10:00:00Z',
    lastLogin: '2024-11-15T16:30:00Z',
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    name: 'Korean Beginner Level 1',
    level: 'Beginner',
    description: 'Introduction to Korean alphabet (Hangul) and basic greetings',
    fee: 299,
    schedule: 'Mon, Wed, Fri 10:00-11:30',
    teacherId: '2',
    teacherName: 'Jane Smith',
    resources: ['textbook.pdf', 'audio_lesson1.mp3'],
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    name: 'Korean Intermediate Conversation',
    level: 'Intermediate',
    description: 'Advanced conversation skills and grammar',
    fee: 399,
    schedule: 'Tue, Thu 14:00-16:00',
    teacherId: '2',
    teacherName: 'Jane Smith',
    resources: ['workbook.pdf', 'video_lesson1.mp4'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Korean Speaking Practice',
    level: 'Speaking',
    description: 'Intensive speaking practice with native speakers',
    fee: 349,
    schedule: 'Mon, Wed, Fri 18:00-19:30',
    teacherId: '2',
    teacherName: 'Jane Smith',
    resources: ['conversation_guide.pdf'],
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'TOPIK Preparation Level 3-4',
    level: 'TOPIK',
    description: 'Comprehensive preparation for TOPIK exam levels 3-4',
    fee: 449,
    schedule: 'Sat, Sun 10:00-13:00',
    teacherId: '2',
    teacherName: 'Jane Smith',
    resources: ['topik_practice.pdf', 'mock_exam1.pdf'],
    createdAt: '2024-02-10T10:00:00Z',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: '1',
    studentId: '3',
    studentName: 'Alice Johnson',
    studentEmail: 'alice@example.com',
    studentPhone: '+1-234-567-8902',
    studentAddress: '123 Main Street, New York, NY 10001',
    courseId: '1',
    courseName: 'Korean Beginner Level 1',
    status: 'approved',
    progress: 75,
    enrolledAt: '2024-03-10T10:00:00Z',
  },
  {
    id: '2',
    studentId: '6',
    studentName: 'David Lee',
    studentEmail: 'david.lee@example.com',
    studentPhone: '+1-234-567-8906',
    studentAddress: '456 Oak Avenue, Los Angeles, CA 90001',
    courseId: '2',
    courseName: 'Korean Intermediate Conversation',
    status: 'pending',
    progress: 0,
    enrolledAt: '2024-12-19T10:00:00Z',
  },
  {
    id: '3',
    studentId: '7',
    studentName: 'Emma Wilson',
    studentEmail: 'emma.wilson@example.com',
    studentPhone: '+1-234-567-8907',
    studentAddress: '789 Pine Road, Chicago, IL 60601',
    courseId: '3',
    courseName: 'Korean Speaking Practice',
    status: 'approved',
    progress: 50,
    enrolledAt: '2024-11-15T10:00:00Z',
  },
  {
    id: '4',
    studentId: '8',
    studentName: 'Frank Miller',
    studentEmail: 'frank.miller@example.com',
    studentPhone: '+1-234-567-8908',
    studentAddress: '321 Elm Street, Houston, TX 77001',
    courseId: '4',
    courseName: 'TOPIK Preparation Level 3-4',
    status: 'pending',
    progress: 0,
    enrolledAt: '2024-09-01T10:00:00Z',
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: '1',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    phone: '+1-234-567-8905',
    subject: 'Course Inquiry',
    message: 'I would like to know more about the beginner course schedule.',
    status: 'pending',
    createdAt: '2024-12-19T10:00:00Z',
  },
  {
    id: '2',
    name: 'Tom Hanks',
    email: 'tom@example.com',
    phone: '+1-234-567-8906',
    subject: 'Enrollment Question',
    message: 'What documents do I need for enrollment?',
    status: 'replied',
    createdAt: '2024-12-18T10:00:00Z',
    repliedAt: '2024-12-18T14:00:00Z',
    replyMessage: 'You need a valid ID and proof of payment.',
  },
  {
    id: '3',
    name: 'Lisa Park',
    email: 'lisa@example.com',
    phone: '+1-234-567-8907',
    subject: 'TOPIK Course',
    message: 'When is the next TOPIK preparation course starting?',
    status: 'closed',
    createdAt: '2024-12-15T10:00:00Z',
    repliedAt: '2024-12-15T15:00:00Z',
    replyMessage: 'The next course starts on January 15, 2025.',
  },
];

export const mockTimetables: Timetable[] = [
  {
    id: '1',
    courseId: '1',
    courseName: 'Korean Beginner Level 1',
    level: 'Beginner',
    teacherId: '2',
    teacherName: 'Jane Smith',
    room: 'Room 101',
    startTime: '10:00',
    endTime: '11:30',
    dayOfWeek: 'Monday',
    occupancy: 12,
    maxOccupancy: 20,
  },
  {
    id: '2',
    courseId: '1',
    courseName: 'Korean Beginner Level 1',
    level: 'Beginner',
    teacherId: '2',
    teacherName: 'Jane Smith',
    room: 'Room 101',
    startTime: '10:00',
    endTime: '11:30',
    dayOfWeek: 'Wednesday',
    occupancy: 12,
    maxOccupancy: 20,
  },
  {
    id: '3',
    courseId: '2',
    courseName: 'Korean Intermediate Conversation',
    level: 'Intermediate',
    teacherId: '2',
    teacherName: 'Jane Smith',
    room: 'Room 202',
    startTime: '14:00',
    endTime: '16:00',
    dayOfWeek: 'Tuesday',
    occupancy: 8,
    maxOccupancy: 15,
  },
];

export const mockContent: Content[] = [
  {
    id: '1',
    type: 'photo',
    title: 'Class Photo - Beginner Level',
    category: 'class',
    url: '/images/class1.jpg',
    thumbnail: '/images/class1-thumb.jpg',
    description: 'Students practicing Hangul',
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: '2',
    type: 'video',
    title: 'Cultural Event - Korean Festival',
    category: 'cultural_event',
    url: '/videos/festival.mp4',
    thumbnail: '/videos/festival-thumb.jpg',
    description: 'Annual Korean cultural festival',
    createdAt: '2024-11-15T10:00:00Z',
  },
  {
    id: '3',
    type: 'photo',
    title: 'TOPIK Achievement',
    category: 'achievement',
    url: '/images/topik-success.jpg',
    thumbnail: '/images/topik-success-thumb.jpg',
    description: 'Students who passed TOPIK Level 4',
    createdAt: '2024-12-10T10:00:00Z',
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    userId: '1',
    userName: 'John Doe',
    action: 'Created',
    target: 'User: Alice Johnson',
    timestamp: '2024-12-20T09:00:00Z',
    ipAddress: '192.168.1.1',
  },
  {
    id: '2',
    userId: '4',
    userName: 'Bob Williams',
    action: 'Updated',
    target: 'Course: Korean Beginner Level 1',
    timestamp: '2024-12-20T08:30:00Z',
    ipAddress: '192.168.1.2',
  },
  {
    id: '3',
    userId: '1',
    userName: 'John Doe',
    action: 'Approved',
    target: 'Enrollment: David Lee',
    timestamp: '2024-12-19T15:00:00Z',
    ipAddress: '192.168.1.1',
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalUsers: 150,
  totalEnrollments: 89,
  activeUsers: 142,
  pendingEnrollments: 5,
  enrollmentTrends: {
    daily: [
      { date: '2024-12-15', count: 3 },
      { date: '2024-12-16', count: 5 },
      { date: '2024-12-17', count: 2 },
      { date: '2024-12-18', count: 7 },
      { date: '2024-12-19', count: 4 },
      { date: '2024-12-20', count: 6 },
    ],
    weekly: [
      { week: 'Week 1', count: 15 },
      { week: 'Week 2', count: 22 },
      { week: 'Week 3', count: 18 },
      { week: 'Week 4', count: 27 },
    ],
    monthly: [
      { month: 'Sep 2024', count: 45 },
      { month: 'Oct 2024', count: 52 },
      { month: 'Nov 2024', count: 61 },
      { month: 'Dec 2024', count: 89 },
    ],
  },
  popularCourse: {
    courseId: '1',
    courseName: 'Korean Beginner Level 1',
    enrollmentCount: 35,
  },
  conversionRate: 12.5,
};

